package org.kidsfirstdrc.dwh.testutils.join

case class JoinVariantOutput(chromosome: String = "2",
                             start: Long = 165310406,
                             end: Long = 165310406,
                             reference: String = "G",
                             alternate: String = "A",
                             name: String = "rs1057520413",
                             hgvsg: String = "chr2:g.166166916G>A",
                             variant_class: String = "SNV",
                             hmb_ac: Long = 1,
                             hmb_an: Long = 2,
                             hmb_af: BigDecimal = 0.5,
                             hmb_homozygotes: Long = 1,
                             hmb_heterozygotes: Long = 1,
                             gru_ac: Long = 0,
                             gru_an: Long = 0,
                             gru_af: BigDecimal = 0,
                             gru_homozygotes: Long = 0,
                             gru_heterozygotes: Long = 0,
                             one_thousand_genomes: Option[OneThousandGenomesFreq] = Some(OneThousandGenomesFreq(20, 10, 0.5)),
                             topmed: Option[Freq] = Some(Freq(20, 10, 0.5, 10, 10)),
                             gnomad_genomes_2_1: Option[GnomadFreq] = Some(GnomadFreq(10, 20, 0.5, 10)),
                             gnomad_exomes_2_1: Option[GnomadFreq] = Some(GnomadFreq(10, 20, 0.5, 10)),
                             gnomad_genomes_3_0: Option[GnomadFreq] = Some(GnomadFreq(10, 20, 0.5, 10)),
                             clinvar_id: Option[String] = Some("RCV000436956"),
                             clin_sig: Option[String] = Some("Pathogenic"),
                             dbsnp_id: Option[String] = Some("rs1234567"),
                             hmb_ac_by_study: Map[String, Long],
                             hmb_an_by_study: Map[String, Long],
                             hmb_af_by_study: Map[String, BigDecimal],
                             hmb_homozygotes_by_study: Map[String, Long],
                             hmb_heterozygotes_by_study: Map[String, Long],
                             gru_ac_by_study: Map[String, Long],
                             gru_an_by_study: Map[String, Long],
                             gru_af_by_study: Map[String, BigDecimal],
                             gru_homozygotes_by_study: Map[String, Long],
                             gru_heterozygotes_by_study: Map[String, Long],
                             studies: Set[String],
                             consent_codes: Set[String],
                             consent_codes_by_study: Map[String, Set[String]],
                             release_id: String = "RE_ABCDEF")

case class OneThousandGenomesFreq(an: Long = 20,
                                  ac: Long = 10,
                                  af: BigDecimal = 0.5)

case class GnomadFreq(ac: Long = 10,
                      an: Long = 20,
                      af: BigDecimal = 0.5,
                      hom: Long = 10)

case class Freq(an: Long = 20,
                ac: Long = 10,
                af: BigDecimal = 0.5,
                homozygotes: Long = 10,
                heterozygotes: Long = 10)
