package org.kidsfirstdrc.dwh.testutils

object Model {


  case class VariantInput(chromosome: String = "2",
                          start: Long = 165310406,
                          end: Long = 165310406,
                          reference: String = "G",
                          alternate: String = "A",
                          hgvsg: String = "chr2:g.166166916G>A",
                          name: Option[String] = Some("rs1057520413"),
                          variant_class: String = "SNV",
                          zygosity: String = "HOM",
                          has_alt: Int = 1,
                          is_hmb: Boolean = true,
                          is_gru: Boolean = false,
                          study_id: String = "SD_123456",
                          release_id: String = "RE_ABCDEF",
                          dbgap_consent_code: String = "SD_123456.c1")

  case class VariantOutput(chromosome: String = "2",
                           start: Long = 165310406,
                           end: Long = 165310406,
                           reference: String = "G",
                           alternate: String = "A",
                           hgvsg: String = "chr2:g.166166916G>A",
                           name: Option[String] = Some("rs1057520413"),
                           hmb_ac: Long = 2,
                           hmb_an: Long = 2,
                           hmb_af: BigDecimal = 1,
                           hmb_homozygotes: Long = 1,
                           hmb_heterozygotes: Long = 0,
                           gru_ac: Long = 0,
                           gru_an: Long = 0,
                           gru_af: BigDecimal = 0,
                           gru_homozygotes: Long = 0,
                           gru_heterozygotes: Long = 0,
                           variant_class: String = "SNV",
                           study_id: String = "SD_123456",
                           release_id: String = "RE_ABCDEF",
                           consent_codes: Set[String] = Set("SD_123456.c1"),
                           consent_codes_by_study: Map[String, Set[String]] = Map("SD_123456" -> Set("SD_123456.c1")))

  case class OccurrencesOutput(chromosome: String,
                               start: Long,
                               end: Long,
                               reference: String,
                               alternate: String,
                               name: Option[String],
                               biospecimen_id: String,
                               participant_id: String,
                               family_id: Option[String],
                               study_id: String,
                               release_id: String,
                               file_name: String,
                               dbgap_consent_code: String)

  case class ConsequencesRowInput(chromosome: String = "2",
                                  start: Long = 165310406,
                                  end: Long = 165310406,
                                  reference: String = "G",
                                  alternate: String = "A",
                                  name: String = "rs1057520413",
                                  annotations: Seq[ConsequenceInput] = Seq(ConsequenceInput()),
                                  splitFromMultiAllelic: Boolean = false)

  case class Genotype(calls: Array[Int])

  val hom_00: Genotype = Genotype(Array(0, 0))
  val hom_11: Genotype = Genotype(Array(1, 1))
  val het_01: Genotype = Genotype(Array(0, 1))
  val het_10: Genotype = Genotype(Array(1, 0))

  val unk: Genotype = Genotype(Array(-1, 0))

  case class Exon(rank: Int, total: Int)

  case class Intron(rank: Int, total: Int)

  case class RefAlt(reference: String, variant: String)

  case class ConsequenceOutput(chromosome: String = "2",
                               start: Long = 165310406,
                               end: Long = 165310406,
                               reference: String = "G",
                               alternate: String = "A",
                               symbol: String = "SCN2A",
                               impact: String = "MODERATE",
                               ensembl_gene_id: String = "ENSG00000136531",
                               ensembl_transcript_id: Option[String] = Some("ENST00000283256.10"),
                               ensembl_regulatory_id: Option[String] = None,
                               feature_type: String = "Transcript",
                               consequences: Seq[String] = Seq("missense_variant"),
                               biotype: Option[String] = Some("protein_coding"),
                               name: Option[String] = Some("rs1057520413"),
                               variant_class: String = "SNV",
                               strand: Int = 1,
                               hgvsg: Option[String] = Some("chr2:g.166166916G>A"),
                               hgvsc: Option[String] = Some("ENST00000283256.10:c.781G>A"),
                               hgvsp: Option[String] = Some("ENSP00000283256.6:p.Val261Met"),
                               exon: Option[Exon] = Some(Exon(7, 27)),
                               intron: Option[Intron] = None,
                               cdna_position: Option[Int] = Some(937),
                               cds_position: Option[Int] = Some(781),
                               amino_acids: Option[RefAlt] = Some(RefAlt("V", "M")),
                               codons: Option[RefAlt] = Some(RefAlt("GTG", "ATG")),
                               protein_position: Option[Int] = Some(261),
                               canonical: Boolean = true,
                               study_id: String = "SD_123456",
                               release_id: String = "RE_ABCDEF")


  case class ConsequenceInput(Allele: String = "A",
                              Consequence: Seq[String] = Seq("missense_variant"),
                              SYMBOL: String = "SCN2A",
                              Gene: String = "ENSG00000136531",
                              Feature: String = "ENST00000283256.10",
                              IMPACT: String = "MODERATE",
                              BIOTYPE: String = "protein_coding",
                              Feature_type: String = "Transcript",
                              STRAND: Int = 1,
                              VARIANT_CLASS: String = "SNV",
                              HGVSg: String = "chr2:g.166166916G>A",
                              HGVSc: String = "ENST00000283256.10:c.781G>A",
                              HGVSp: String = "ENSP00000283256.6:p.Val261Met",
                              CANONICAL: String = "YES",
                              cDNA_position: Option[Int] = Some(937),
                              CDS_position: Option[Int] = Some(781),
                              Amino_acids: Option[RefAlt] = Some(RefAlt("V", "M")),
                              Protein_position: Option[Int] = Some(261),
                              Codons: Option[RefAlt] = Some(RefAlt("GTG", "ATG")),
                              EXON: Option[Exon] = Some(Exon(7, 27)),
                              INTRON: Option[Intron] = None)

  case class JoinVariantOutput(chromosome: String = "2",
                               start: Long = 165310406,
                               end: Long = 165310406,
                               reference: String = "G",
                               alternate: String = "A",
                               name: String = "rs1057520413",
                               hgvsg: String = "chr2:g.166166916G>A",
                               variant_class: String = "SNV",
                               hmb_ac: Long = 1,
                               hmb_an: Long = 2,
                               hmb_af: BigDecimal = 0.5,
                               hmb_homozygotes: Long = 1,
                               hmb_heterozygotes: Long = 1,
                               gru_ac: Long = 0,
                               gru_an: Long = 0,
                               gru_af: BigDecimal = 0,
                               gru_homozygotes: Long = 0,
                               gru_heterozygotes: Long = 0,
                               //1k_genomes: Option[Freq] = Some(Freq(20, 10, 0.5, Some(10), Some(10))),
                               one_k_genomes: Option[ThousandGenomesFreq] = Some(ThousandGenomesFreq(20, 10, 0.5)),
                               topmed: Option[Freq] = Some(Freq(20, 10, 0.5, 10, 10)),
                               gnomad_genomes_2_1: Option[GnomadFreq] = Some(GnomadFreq(20, 10, 0.5, 10)),
                               gnomad_exomes_2_1: Option[GnomadFreq] = Some(GnomadFreq(20, 10, 0.5, 10)),
                               gnomad_genomes_3_0: Option[GnomadFreq] = Some(GnomadFreq(20, 10, 0.5, 10)),
                               clinvar_id: Option[String] = Some("RCV000436956"),
                               clin_sig: Option[String] = Some("Pathogenic"),
                               dbsnp_id: Option[String] = Some("rs1234567"),
                               hmb_ac_by_study: Map[String, Long],
                               hmb_an_by_study: Map[String, Long],
                               hmb_af_by_study: Map[String, BigDecimal],
                               hmb_homozygotes_by_study: Map[String, Long],
                               hmb_heterozygotes_by_study: Map[String, Long],
                               gru_ac_by_study: Map[String, Long],
                               gru_an_by_study: Map[String, Long],
                               gru_af_by_study: Map[String, BigDecimal],
                               gru_homozygotes_by_study: Map[String, Long],
                               gru_heterozygotes_by_study: Map[String, Long],
                               studies: Set[String],
                               consent_codes: Set[String],
                               consent_codes_by_study: Map[String, Set[String]],
                               release_id: String = "RE_ABCDEF"
                              )

  case class JoinConsequenceOutput(chromosome: String = "2",
                                   start: Long = 165310406,
                                   end: Long = 165310406,
                                   reference: String = "G",
                                   alternate: String = "A",
                                   symbol: String = "SCN2A",
                                   impact: String = "MODERATE",
                                   ensembl_gene_id: String = "ENSG00000136531",
                                   ensembl_transcript_id: Option[String] = Some("ENST00000283256.10"),
                                   ensembl_regulatory_id: Option[String] = None,
                                   feature_type: String = "Transcript",
                                   consequences: Seq[String] = Seq("missense_variant"),
                                   biotype: Option[String] = Some("protein_coding"),
                                   name: Option[String] = Some("rs1057520413"),
                                   variant_class: String = "SNV",
                                   strand: Int = 1,
                                   hgvsg: Option[String] = Some("chr2:g.166166916G>A"),
                                   hgvsc: Option[String] = Some("ENST00000283256.10:c.781G>A"),
                                   hgvsp: Option[String] = Some("ENSP00000283256.6:p.Val261Met"),
                                   exon: Option[Exon] = Some(Exon(7, 27)),
                                   intron: Option[Intron] = None,
                                   cdna_position: Option[Int] = Some(937),
                                   cds_position: Option[Int] = Some(781),
                                   amino_acids: Option[RefAlt] = Some(RefAlt("V", "M")),
                                   codons: Option[RefAlt] = Some(RefAlt("GTG", "ATG")),
                                   protein_position: Option[Int] = Some(261),
                                   study_ids: Set[String] = Set("SD_123456"),
                                   release_id: String = "RE_ABCDEF",
                                   //sift_score: Option[Double] = Some(0.99),
                                   aa_change: Option[String] = Some("V261M"),
                                   coding_dna_change: Option[String] = Some("781G>A"),
                                   canonical: Boolean = true,
                                  //Scores from DBNSFP
                                   BayesDel_addAF_pred: Option[String] = None,
                                   BayesDel_addAF_rankscore: Option[String] = None,
                                   BayesDel_addAF_score: Option[String] = None,
                                   BayesDel_noAF_pred: Option[String] = None,
                                   BayesDel_noAF_rankscore: Option[String] = None,
                                   BayesDel_noAF_score: Option[String] = None,
                                   CADD_phred: Option[String] = None,
                                   CADD_raw: Option[String] = None,
                                   CADD_raw_rankscore: Option[String] = Some("CADD_raw_rankscore"),
                                   ClinPred_pred: Option[String] = None,
                                   ClinPred_rankscore: Option[String] = None,
                                   ClinPred_score: Option[String] = None,
                                   DANN_rankscore: Option[String] = Some("DANN_rankscore"),
                                   DANN_score: Option[String] = None,
                                   DEOGEN2_pred: Option[String] = None,
                                   DEOGEN2_rankscore: Option[String] = None,
                                   DEOGEN2_score: Option[String] = None,
                                   `Eigen-PC-phred_coding`: Option[String] = None,
                                   `Eigen-PC-raw_coding`: Option[String] = None,
                                   `Eigen-PC-raw_coding_rankscore`: Option[String] = None,
                                   `Eigen-phred_coding`: Option[String] = None,
                                   `Eigen-raw_coding`: Option[String] = None,
                                   `Eigen-raw_coding_rankscore`: Option[String] = None,
                                   FATHMM_converted_rankscore: Option[String] = Some("FATHMM_rankscore"),
                                   FATHMM_pred: Option[String] = Some("FATHMM_pred"),
                                   FATHMM_score: Option[String] = None,
                                   `GERP++_NR`: Option[String] = None,
                                   `GERP++_RS`: Option[String] = None,
                                   `GERP++_RS_rankscore`: Option[String] = None,
                                   GM12878_confidence_value: Option[String] = None,
                                   GM12878_fitCons_rankscore: Option[String] = None,
                                   GM12878_fitCons_score: Option[String] = None,
                                   GTEx_V8_gene: List[String] = null,
                                   GTEx_V8_tissue: List[String] = null,
                                   GenoCanyon_rankscore: Option[String] = None,
                                   GenoCanyon_score: Option[String] = None,
                                   `H1-hESC_confidence_value`: Option[String] = None,
                                   `H1-hESC_fitCons_rankscore`: Option[String] = None,
                                   `H1-hESC_fitCons_score`: Option[String] = None,
                                   HUVEC_confidence_value: Option[String] = None,
                                   HUVEC_fitCons_rankscore: Option[String] = None,
                                   HUVEC_fitCons_score: Option[String] = None,
                                   Interpro_domain: Option[String] = None,
                                   LINSIGHT: Option[String] = None,
                                   LINSIGHT_rankscore: Option[String] = None,
                                   `LIST-S2_pred`: Option[String] = None,
                                   `LIST-S2_rankscore`: Option[String] = None,
                                   `LIST-S2_score`: Option[String] = None,
                                   LRT_converted_rankscore: Option[Double] = Some(0.4),
                                   LRT_pred: Option[String] = Some("LRT_pred"),
                                   `M-CAP_pred`: Option[String] = None,
                                   `M-CAP_rankscore`: Option[Double] = None,
                                   `M-CAP_score`: Option[Double] = None,
                                   MPC_rankscore: Option[Double] = None,
                                   MPC_score: Option[Double] = None,
                                   MVP_rankscore: Option[Double] = None,
                                   MVP_score: Option[Double] = None,
                                   MetaLR_pred: Option[String] = None,
                                   MetaLR_rankscore: Option[Double] = None,
                                   MetaLR_score: Option[Double] = None,
                                   MetaSVM_pred: Option[String] = None,
                                   MetaSVM_rankscore: Option[Double] = None,
                                   MetaSVM_score: Option[Double] = None,
                                   MutPred_rankscore: Option[Double] = None,
                                   MutPred_score: Option[Double] = None,
                                   MutationAssessor_pred: Option[String] = None,
                                   MutationAssessor_rankscore: Option[Double] = None,
                                   MutationAssessor_score: Option[Double] = None,
                                   MutationTaster_converted_rankscore: Option[Double] = None,
                                   PROVEAN_converted_rankscore: Option[Double] = None,
                                   PROVEAN_pred: Option[String] = None,
                                   PROVEAN_score: Option[Double] = None,
                                   Polyphen2_HDIV_pred: Option[String] = None,
                                   Polyphen2_HDIV_rankscore: Option[Double] = None,
                                   Polyphen2_HDIV_score: Option[Double] = None,
                                   Polyphen2_HVAR_pred: Option[String] = Some("HVAR_pred"),
                                   Polyphen2_HVAR_rankscore: Option[Double] = Some(0.2),
                                   Polyphen2_HVAR_score: Option[Double] = None,
                                   PrimateAI_pred: Option[String] = None,
                                   PrimateAI_rankscore: Option[Double] = None,
                                   PrimateAI_score: Option[Double] = None,
                                   REVEL_rankscore: Option[Double] = Some(0.3),
                                   SIFT_converted_rankscore: Option[Double] = Some(0.1),
                                   SIFT_pred: Option[String] = Some("SIFT_pred"),
                                   SIFT_score: Option[Double] = None,
                                   VEST4_rankscore: Option[Double] = None,
                                   VEST4_score: Option[Double] = None,
                                   bStatistic: Option[Double] = None,
                                   bStatistic_converted_rankscore: Option[Double] = None,
                                   `fathmm-MKL_coding_group`: Option[String] = None,
                                   `fathmm-MKL_coding_pred`: Option[String] = None,
                                   `fathmm-MKL_coding_rankscore`: Option[Double] = None,
                                   `fathmm-MKL_coding_score`: Option[Double] = None,
                                   `fathmm-XF_coding_pred`: Option[String] = None,
                                   `fathmm-XF_coding_rankscore`: Option[Double] = None,
                                   `fathmm-XF_coding_score`: Option[Double] = None,
                                   integrated_confidence_value: Option[Double] = None,
                                   integrated_fitCons_rankscore: Option[Double] = None,
                                   integrated_fitCons_score: Option[Double] = None,
                                   phastCons100way_vertebrate: Option[Double] = None,
                                   phastCons100way_vertebrate_rankscore: Option[Double] = None,
                                   phastCons17way_primate: Option[Double] = None,
                                   phastCons17way_primate_rankscore: Option[Double] = None,
                                   phastCons30way_mammalian_rankscore: Option[Double] = None,
                                   phastcons30way_mammalian: Option[Double] = None,
                                   phyloP100way_vertebrate: Option[Double] = None,
                                   phyloP100way_vertebrate_rankscore: Option[Double] = None,
                                   phyloP17way_primate: Option[Double] = None,
                                   phyloP17way_primate_rankscore: Option[Double] = Some(0.5),
                                   phyloP30way_mammalian: Option[Double] = None,
                                   phyloP30way_mammalian_rankscore: Option[Double] = None)

  case class DBNSFPScore(chromosome: String = "2",
                         start: Long = 165310406,
                         reference: String = "G",
                         alternate: String = "A",
                         symbol: String = "SCN2A",
                         ensembl_gene_id: String = "ENSG00000136531",
                         ensembl_transcript_id: Option[String] = Some("ENST00000283256.10"),
                         ensembl_protein_id: Option[String] = None,
                         cds_strand: Option[Int] = None,
                         sift_score: Option[Double] = Some(0.99)
                        )

  case class ThousandGenomesFreq(an: Long = 20,
                                 ac: Long = 10,
                                 af: BigDecimal = 0.5)

  case class GnomadFreq(an: Long = 20,
                        ac: Long = 10,
                        af: BigDecimal = 0.5,
                        homozygotes: Long = 10)

  case class Freq(an: Long = 20,
                  ac: Long = 10,
                  af: BigDecimal = 0.5,
                  homozygotes: Long = 10,
                  heterozygotes: Long = 10)

  case class GnomadFrequencyEntry(chromosome: String = "2",
                                  start: Long = 165310406,
                                  reference: String = "G",
                                  alternate: String = "A",
                                  ac: Long = 10,
                                  an: Long = 20,
                                  af: BigDecimal = 0.5,
                                  hom: Long = 10)

  case class FrequencyEntry(chromosome: String = "2",
                            start: Long = 165310406,
                            end: Long = 165310406,
                            reference: String = "G",
                            alternate: String = "A",
                            ac: Long = 10,
                            an: Long = 20,
                            af: BigDecimal = 0.5,
                            homozygotes: Long = 10,
                            heterozygotes: Long = 10)

  case class ClinvarEntry(chromosome: String = "2",
                          start: Long = 165310406,
                          end: Long = 165310406,
                          reference: String = "G",
                          alternate: String = "A",
                          name: String = "RCV000436956",
                          clin_sig: String = "Pathogenic")

  case class DBSNPEntry(chromosome: String = "2",
                        start: Long = 165310406,
                        end: Long = 165310406,
                        reference: String = "G",
                        alternate: String = "A",
                        name: String = "rs1234567")

  case class ParticipantInput(kf_id: String = "PT_001", family_id: String = "FM_001", affected_status: String = "alive")

  case class BiospecimenInput(kf_id: String = "BS_0001", participant_id: String = "PT_001")

  case class ParticipantOutput(kf_id: String = "PT_001", family_id: String = "FM_001", affected_status: String = "alive", study_id: String = "SD_123", release_id: String = "RE_ABCDEF")

  case class BiosepecimenOutput(kf_id: String = "BS_0001", biospecimen_id: String = "BS_0001", participant_id: String = "PT_001", family_id: String = "FM_001", study_id: String = "SD_123", release_id: String = "RE_ABCDEF")

}
