package org.kidsfirstdrc.dwh.testutils

case class VariantOutput(chromosome: String = "2",
                         start: Long = 165310406,
                         end: Long = 165310406,
                         reference: String = "G",
                         alternate: String = "A",
                         hgvsg: String = "chr2:g.166166916G>A",
                         name: Option[String] = Some("rs1057520413"),
                         hmb_ac: Long = 2,
                         hmb_an: Long = 2,
                         hmb_af: BigDecimal = 1,
                         hmb_homozygotes: Long = 1,
                         hmb_heterozygotes: Long = 0,
                         gru_ac: Long = 0,
                         gru_an: Long = 0,
                         gru_af: BigDecimal = 0,
                         gru_homozygotes: Long = 0,
                         gru_heterozygotes: Long = 0,
                         variant_class: String = "SNV",
                         study_id: String = "SD_123456",
                         release_id: String = "RE_ABCDEF",
                         consent_codes: Set[String] = Set("SD_123456.c1"),
                         consent_codes_by_study: Map[String, Set[String]] = Map("SD_123456" -> Set("SD_123456.c1")))
